// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'browserContainer': string;
  'browserHeader': string;
  'browserHeaderBottom': string;
  'browserHeaderButtons': string;
  'browserHeaderTitle': string;
  'browserHeaderTop': string;
  'browserInput': string;
  'buttonArea': string;
  'content': string;
}
export const cssExports: CssExports;
export default cssExports;
