// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'browser-mockup': string;
  'with-tab': string;
  'with-url': string;
}
export const cssExports: CssExports;
export default cssExports;
