// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card': string;
  'container': string;
  'desc': string;
  'introduction': string;
  'name': string;
  'nav': string;
  'navItem': string;
}
export const cssExports: CssExports;
export default cssExports;
