// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'row': string;
  'rowAlignBottom': string;
  'rowAlignMiddle': string;
  'rowAlignTop': string;
  'rowCenter': string;
  'rowJustifyCenter': string;
  'rowJustifyEnd': string;
  'rowJustifySpaceAround': string;
  'rowJustifySpaceBetween': string;
  'rowJustifyStart': string;
}
export const cssExports: CssExports;
export default cssExports;
