// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'row': string;
  'row-align-bottom': string;
  'row-align-middle': string;
  'row-align-top': string;
  'row-center': string;
  'row-justify-center': string;
  'row-justify-end': string;
  'row-justify-space-around': string;
  'row-justify-space-between': string;
  'row-justify-start': string;
}
export const cssExports: CssExports;
export default cssExports;
