# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
- lts/*

install:
  - yarn install # npm ci
script:
  - yarn build # npm run build
  - commitlint-travis

cache: true

deploy:
  provider: pages
  target_branch: master
  on:
    branch: develop
    skip_cleanup: true
  local_dir: dist
  token: $GITHUB_TOKEN
  keep_history: true
  committer_from_gh: true
