# 使用最新的 LTS Node.js版本
# https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
language: node_js
node_js:
  - lts/*

# 运行脚本
install:
  - yarn install # npm ci
script:
  - yarn build # npm run build
  - commitlint-travis

# 部署信息
deploy:
  provider: pages

  # 将 `local_dir` 内容推送到 `target_branch` 分支, 默认为: gh-pages
  target_branch: master
  on:
    branch: develop

  # 确保 skip_cleanup 设置为 true
  # 否则 Travis CI 会删除在构建期间创建的所有文件，这可能会删除正在尝试上传的文件。
  skip_cleanup: true

  # 要推送到 GitHub Pages 的目录，默认为当前目录(.)。
  # 可以指定为当前目录的绝对路径或相对路径
  local_dir: dist

  # 在 GitHub 中生成，用于允许 Travis 向你的仓库推送代码。
  # 在 [Travis](https://travis-ci.com/) 的项目设置页面进行配置，设置为 secure variable
  # NOTE: 后台设置环境变量时不用带 $
  token: $GITHUB_TOKEN

  # 创建增量提交而不是强制推送，默认为false
  keep_history: true

  # 允许使用令牌的所有者名称和电子邮件进行 commit
  committer_from_gh: true
