// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'active': string;
  'collapsed': string;
  'disabled': string;
  'icon': string;
  'menuItem': string;
  'submenuArrow': string;
  'submenuItem': string;
  'submenuTitle': string;
}
export const cssExports: CssExports;
export default cssExports;
