// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'desc': string;
  'index': string;
  'item': string;
  'name': string;
  'open': string;
  'open-active': string;
  'panel': string;
  'panel1': string;
  'panel2': string;
  'panel3': string;
  'panel4': string;
  'panel5': string;
  'panels': string;
}
export const cssExports: CssExports;
export default cssExports;
