// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'listItem': string;
  'listItemChild': string;
  'listItemSubContent': string;
  'skeleton-loading': string;
}
export const cssExports: CssExports;
export default cssExports;
