// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'card': string;
  'cardHeader': string;
  'title': string;
  'titleInner': string;
}
export const cssExports: CssExports;
export default cssExports;
