// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'btn-1': string;
  'btn-2': string;
  'btn-3': string;
  'btn-4': string;
  'btn-5': string;
  'buttons': string;
  'container': string;
}
export const cssExports: CssExports;
export default cssExports;
