// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'browserFrame': string;
  'container': string;
  'fullContent': string;
  'iframe': string;
}
export const cssExports: CssExports;
export default cssExports;
