// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'aside': string;
  'aside-left': string;
  'aside-left-1': string;
  'aside-right': string;
  'aside-right-1': string;
  'footer': string;
  'header': string;
  'main': string;
  'row-padding-left': string;
  'row-padding-left-x2': string;
  'row-padding-right': string;
  'row-padding-right-x2': string;
}
export const cssExports: CssExports;
export default cssExports;
